name:                bst-next
version:             0.1.0.0
github:              "bcherny/bst-next"
license:             MIT
author:              "Boris Cherny"
maintainer:          "boris@performancejs.com"
copyright:           "2018 Boris Cherny"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bcherny/bst-next#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bst-next-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bst-next

tests:
  bst-next-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bst-next
